name: order-food-app
services:
  frontend:
    build: ./frontend
    ports: 
      - "8080:8080"
    environment:
      - VUE_APP_BACKEND_URL=http://localhost:3000
    depends_on:
      - backend

  backend:
    build: ./backend
    environment:
      - MONGODB_CONNECTION_STRING=mongodb://mongodb:27017/projectz
    ports: 
      - "3000:3000"
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db